
---
#loggingOption: AllCallsWithDetails
loggingOption: AllCalls
#loggingOption: OnlyLimited
# OnlyLimited is the default

credentialID: 'JWT:Claims+"sub"\s*:\s*"(.*?)"'

limiterMappings:
  - name: AuthToken
    withCallerRemoteAddressID: 50r/s
    pathSelectors:
      - "equals:/oauth/token"
  - name: AuthAuthorize
    withCallerRemoteAddressID: 50r/s
    pathSelectors:
      - "equals:/oauth/authorize"
  - name: LoginPage
    withCallerRemoteAddressID: 50r/1s
    pathSelectors:
      - "equals:/login"
  - name: LoginDo
    withCallerRemoteAddressID: 50r/s
    pathSelectors:
      - "equals:/login.do"
  - name: info
    withCallerRemoteAddressID: 10r/s
    pathSelectors:
      - "equals:/info"
  - name: SCIM
    withCallerCredentialsID: 200r/s
    pathSelectors:
      - "startsWith:/Users"
      - "startsWith:/Groups"
  - name: EverythingElse
    global: 200r/s
    pathSelectors:
      - "other"
