---
apiVersion: v1
kind: Service
metadata:
  name: prom-deployment
  labels:
    app: prom
spec:
  type: ClusterIP
  ports:
  - port: 9090
    name: prom-metrics
    targetPort: 9090
    protocol: TCP
  selector:
    app: prom