---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-config
data:
  prometheus.yml: |
    scrape_configs:
    - job_name: uaa
      static_configs:
      - targets:
        - 10.101.116.68:9102
        labels:
          uaa: uaa