#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def encryption_keys():
encryption: #@ data.values.encryption
#@ end

---
apiVersion: v1
kind: Secret
metadata:
  name: encryption-keys
type: Opaque
stringData:
  encryption_keys.yml: #@ yaml.encode(encryption_keys())
