---
apiVersion: v1
kind: Secret
metadata:
  name: encryption-keys
type: Opaque
stringData:
  encryption_keys.yml: |
    encryption:
      active_key_label: CHANGE-THIS-KEY
      encryption_keys:
        - label: CHANGE-THIS-KEY
          passphrase: CHANGEME